<?php
if ( ! defined( 'ABSPATH' ) || !is_user_logged_in()  ) exit; // Exit if accessed directly
get_header();
?>
<div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">
        <article class="hentry">
            
        <?php
        // list of items
        require_once('Walker_Category_Posts.php');
        echo '<ul class="scwp-item-list">';
        $walker = new Walker_Category_Posts;
        $cats = wp_list_categories(array(
            'taxonomy'=>'shared_item_category',
            'title_li'=>'',
            'walker' => $walker,
            'echo'=>false,
        ));
        // hide "No category" default text
        if($cats!='<li class="cat-item-none">'.__('No categories').'</li>'){
            echo $cats;
        }
        // display items without category
        $dummy=null;
        echo $walker->start_el($dummy, null);
        echo '</ul>';

        // you can also try this without using wp_list_categories and the custom walker
        /*$categories = get_terms( array(
            'taxonomy' => 'shared_item_category',
            'orderby' => 'name', 
            'order' => 'asc'
        ) );
        foreach ($categories as $cat){
            echo "<h3 class='switcher' data-link='$cat->slug'>$cat->name</h3>";
            echo '<ul class="products-list" data-block="'.$cat->slug.'">';
            $args = array( 
                'posts_per_page' => -1, 
                'shared_item_category' => $cat->slug, 
                'post_type' => 'shared_item',
                'orderby' => 'name', 
                'order' => 'asc'
            );
            $myposts = get_posts( $args );
            foreach ( $myposts as $post ) : setup_postdata( $post );
                $query = "SELECT 
                CASE WHEN comment_date = 0 THEN 'requested'
                WHEN comment_date_gmt > CURRENT_TIMESTAMP OR comment_date_gmt = 0 THEN 'na'
                ELSE 'available' END availability 
                FROM $wpdb->comments WHERE comment_post_ID = $post->ID AND comment_type = 'lending' LIMIT 1";
                $lending = $wpdb->get_row($query);
        ?>
                <li>
                    <div class="thumbnail"><?php the_post_thumbnail('thumbnail'); ?></div>
                    <span class="text"><a href="<?php the_permalink() ?>"><?php the_title() ?></a><br />
                        <?php _e(isset($lending)?$lending->availability:'available', 'sharing-club') ?>
                    </span>
                </li>
            <?php endforeach;
            wp_reset_postdata();
            echo '</ul>';
        }*/
        ?>
        
        </article>
    </main>
</div>
<!-- Generated by Sharing Club <?php echo get_site_option( 'sharing-club_version' ); ?> -->
<?php get_footer();?>